python vnf.py --input ./dataset/cogent_center_0/input.txt --request ./dataset/cogent_center_0/request10.txt
python vnf.py --input ./dataset/cogent_center_0/input.txt --request ./dataset/cogent_center_0/request20.txt
python vnf.py --input ./dataset/cogent_center_0/input.txt --request ./dataset/cogent_center_0/request30.txt
python vnf.py --input ./dataset/cogent_center_1/input.txt --request ./dataset/cogent_center_1/request10.txt
python vnf.py --input ./dataset/cogent_center_1/input.txt --request ./dataset/cogent_center_1/request20.txt
python vnf.py --input ./dataset/cogent_center_1/input.txt --request ./dataset/cogent_center_1/request30.txt
python vnf.py --input ./dataset/cogent_center_2/input.txt --request ./dataset/cogent_center_2/request10.txt
python vnf.py --input ./dataset/cogent_center_2/input.txt --request ./dataset/cogent_center_2/request20.txt
python vnf.py --input ./dataset/cogent_center_2/input.txt --request ./dataset/cogent_center_2/request30.txt
python vnf.py --input ./dataset/cogent_center_3/input.txt --request ./dataset/cogent_center_3/request10.txt
python vnf.py --input ./dataset/cogent_center_3/input.txt --request ./dataset/cogent_center_3/request20.txt
python vnf.py --input ./dataset/cogent_center_3/input.txt --request ./dataset/cogent_center_3/request30.txt
python vnf.py --input ./dataset/cogent_center_4/input.txt --request ./dataset/cogent_center_4/request10.txt
python vnf.py --input ./dataset/cogent_center_4/input.txt --request ./dataset/cogent_center_4/request20.txt
python vnf.py --input ./dataset/cogent_center_4/input.txt --request ./dataset/cogent_center_4/request30.txt
python vnf.py --input ./dataset/cogent_rural_0/input.txt --request ./dataset/cogent_rural_0/request10.txt
python vnf.py --input ./dataset/cogent_rural_0/input.txt --request ./dataset/cogent_rural_0/request20.txt
python vnf.py --input ./dataset/cogent_rural_0/input.txt --request ./dataset/cogent_rural_0/request30.txt
python vnf.py --input ./dataset/cogent_rural_1/input.txt --request ./dataset/cogent_rural_1/request10.txt
python vnf.py --input ./dataset/cogent_rural_1/input.txt --request ./dataset/cogent_rural_1/request20.txt
python vnf.py --input ./dataset/cogent_rural_1/input.txt --request ./dataset/cogent_rural_1/request30.txt
python vnf.py --input ./dataset/cogent_rural_2/input.txt --request ./dataset/cogent_rural_2/request10.txt
python vnf.py --input ./dataset/cogent_rural_2/input.txt --request ./dataset/cogent_rural_2/request20.txt
python vnf.py --input ./dataset/cogent_rural_2/input.txt --request ./dataset/cogent_rural_2/request30.txt
python vnf.py --input ./dataset/cogent_rural_3/input.txt --request ./dataset/cogent_rural_3/request10.txt
python vnf.py --input ./dataset/cogent_rural_3/input.txt --request ./dataset/cogent_rural_3/request20.txt
python vnf.py --input ./dataset/cogent_rural_3/input.txt --request ./dataset/cogent_rural_3/request30.txt
python vnf.py --input ./dataset/cogent_rural_4/input.txt --request ./dataset/cogent_rural_4/request10.txt
python vnf.py --input ./dataset/cogent_rural_4/input.txt --request ./dataset/cogent_rural_4/request20.txt
python vnf.py --input ./dataset/cogent_rural_4/input.txt --request ./dataset/cogent_rural_4/request30.txt
python vnf.py --input ./dataset/cogent_uniform_0/input.txt --request ./dataset/cogent_uniform_0/request10.txt
python vnf.py --input ./dataset/cogent_uniform_0/input.txt --request ./dataset/cogent_uniform_0/request20.txt
python vnf.py --input ./dataset/cogent_uniform_0/input.txt --request ./dataset/cogent_uniform_0/request30.txt
python vnf.py --input ./dataset/cogent_uniform_1/input.txt --request ./dataset/cogent_uniform_1/request10.txt
python vnf.py --input ./dataset/cogent_uniform_1/input.txt --request ./dataset/cogent_uniform_1/request20.txt
python vnf.py --input ./dataset/cogent_uniform_1/input.txt --request ./dataset/cogent_uniform_1/request30.txt
